name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please help us understand your idea.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/your-repo/i18ntk/blob/main/CONTRIBUTING.md)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: A clear and concise description of what the problem is
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this problem?

  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      description: How would this feature impact users?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for adoption
        - Breaking - Would require major changes
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be helpful
      placeholder: |
        1. As a [type of user], I want [goal] so that [benefit]
        2. When [scenario], I need [feature] to [accomplish task]

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share
      placeholder: Any technical considerations or implementation suggestions

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Any additional information