name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify package
        run: npm run verify-package

      - name: Run security audit
        run: |
          npm audit --audit-level=high --json > audit-results.json || true
          if [ -s audit-results.json ]; then
            echo "🔍 Security audit results:"
            cat audit-results.json
            
            # Check for high/critical vulnerabilities
            HIGH_COUNT=$(npm audit --audit-level=high --json | jq '.metadata.vulnerabilities.high // 0' 2>/dev/null || echo "0")
            CRITICAL_COUNT=$(npm audit --audit-level=critical --json | jq '.metadata.vulnerabilities.critical // 0' 2>/dev/null || echo "0")
            
            if [ "$HIGH_COUNT" -gt 0 ] || [ "$CRITICAL_COUNT" -gt 0 ]; then
              echo "❌ Found $HIGH_COUNT high and $CRITICAL_COUNT critical vulnerabilities"
              echo "Please run 'npm audit fix' to address these issues"
              exit 1
            else
              echo "✅ No high or critical vulnerabilities found"
            fi
          else
            echo "✅ No security vulnerabilities detected"
          fi

      - name: Run tests
        run: npm test

      - name: Package verification
        run: |
          echo "✅ All checks passed - ready for manual release"
          echo "To publish manually, run: npm publish"